package com.leafcompany.ohmydog.enumerations;

public enum Zona {
    Plaza_Moreno,
    Plaza_San_Martin,
    Plaza_Malvinas_Argentinas,
    Plaza_Rivadavia,
    Parque_Vucetich,
    Plaza_Rocha,
    Plaza_Italia,
    Parque_Saavedra,
    Plaza_Matheu,
    Plaza_España,
    Plaza_Sarmiento,
    Parque_Castelli,
    Plaza_Peron,
    Plaza_Yrigoyen,
    Plaza_Rosas,
    Plaza_Alsina,
    Plaza_Olazábal,
    Plaza_Belgrano,
    Plaza_Guemes,
    Parque_Alberti,
    Plaza_19_de_Noviembre,
    Plaza_Azcuenaga,
    Plaza_Paso,
}
